### ISSUE TITLE
'warn' option to false still warns

### ISSUE THREAD

**Issue by brynnbp** [kfirba/Mavigator#1]
Setting warnIfLinkWasntFound: false as an option is still giving me a warning in the console. Not a big deal, surrounded it with jQuery to search for the element before mavigating it (since it's not on every page). 

Using Chrome Version 47.0.2526.111 m. Unfortunately don't have time to investigate further, but wanted to let you know. Thanks for the plugin, big time saver for me.

**Comment by kfirba** [comment]
@brynnbp Can you confirm that the message in the console that you've received was: 

> Couldn't find the requested element.

**Comment by kfirba** [comment]
@brynnbp Let me know if it fixed your issue. If it indeed solved it, you can safely remove your jQuery lookup guard to gain some performance.
