### ISSUE TITLE
With translation,

### ISSUE THREAD

**Issue by ahmedalmulki** [kfirba/Mavigator#4]
Hi , 
I am using this library in my laravel project and it's working perfectly , unless when I translated my pages for example "www.example.com/en/test"  how can I solve this , I want this js ignore en or es or anything else ,
Thanks again .

**Comment by kfirba** [comment]
@ahmedalmulki hey. Glad you found this script useful.

One of the options is the `uri` option where you can tell the script to look for a specific link to mark.


When you initialize Mavigator, remove the locale from the the uri to mark:

```
let uriToMark = '/' + window.location.pathname.split('/').slice(2).join('/');

Mavigator.mark('body', {
    uri: uriToMark
});
```

What we do here is we take the full pathname that has the locale in it, we explode it to an array and remove the first 2 elements which are `null` and the locale itself (e.g. `en`) and then we join back the array to a uri string while pretending a backslash. This way, uris like `/en/projects` will simply become `/projects`.

**Comment by ahmedalmulki** [comment]
it's working perfectly , thanks for this wonderful script .
